### PR TITLE
Alignment options and improvements for Library Move Extra Info

### PR DESCRIPTION
**Pull request by rasitayaz**
@MSeys I made some improvements on the positioning and animations as well, can you also test it to see if everything works as expected and check if I have missed anything?

### CODE REVIEW

**Comment by MSeys** [comment]
The only thing bothering me is specific roundedness values now being gone.

**Comment by rasitayaz** [comment]
well, they're still there. if you check the theme.json you'll understand what I mean.

**Comment by rasitayaz** [comment]
I used variable injection instead of css injection, much cleaner this way.

**Comment by MSeys** [comment]
I did look at the theme.json, but they don't have the same as the previous. 15px, etc are missing.

**Comment by rasitayaz** [comment]
oh, I might've missed them, let me add those real quick

**Comment by rasitayaz** [comment]
added them, also added a 0px roundedness if someone wants to use it without radius

**Comment by rasitayaz** [comment]
I think I'm done now, sorry if I made a mess

<details>
  <summary>Final results</summary>

  Image 1
  Image 2
  Image 3
  Image 4
  Image 5
  Image 6
  Image 7

</details>

**Pull request merged**
